'use strict';
var
  should = require('should'),
  libSource = process.env.PAPPEL_COV ? 'build-cov' : 'build';

describe('Pappel2Strings', function() {

  var libLocation = ['../../..', libSource, 'converter/Pappel2Strings'].join('/'),
    Converter = require(libLocation),
    fixturePath = [__dirname, '../..', 'fixtures/'].join('/'),
    fs = require('fs'),
    path = require('path'),
    XLSX = require('xlsx');

  describe('#convert', function() {

    it('should convert the content of one language', function() {
      var conv = new Converter();
      conv.convert({
        pappel: {
          hello: {
            en: 'Hello!',
            fr: 'Bonjour !'
          }
        },
        language: 'fr'
      }).should.eql('"hello" = "Bonjour !";' + "\r\n");

    });

    it('should convert the content with a variable', function() {
      var conv = new Converter();
      conv.convert({
        pappel: {
          hello: {
            en: 'Hello!',
            fr: 'Bonjour ${$1} !'
          }
        },
        language: 'fr'
      }).should.eql('"hello" = "Bonjour %@ !";' + "\r\n");

    });
  });

  describe('#transformString', function() {

    it('should change the Pappel variable', function() {
      var conv = new Converter();
      var inputPath = path.normalize(fixturePath + 'pappel1.json');
      var json = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
      //console.log('XLSX2PappelTest#convert inputPath', inputPath);
      conv.transformString({
        str: 'Hello ${$1s}!'
      }).should.eql('Hello %@s!');

    });
  });


  describe('#wrapContent', function() {

    it('should convert the content of one language', function() {
      var conv = new Converter(),
        content = '"hello" = "Bonjour !";' + "\r\n";
      //var inputPath = path.normalize(fixturePath + 'pappel1.json');
      //var json = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
      //console.log('XLSX2PappelTest#convert inputPath', inputPath);
      conv.wrapContent({
        content: content
      }).should.eql('/*' + "\r\n" + '  Localizable.strings' + "\r\n" + "\r\n" + '  Generated by Pappel.io' + "\r\n" + '  */' + "\r\n" + content);

    });

  });

});
