/**
 * @class Pappel.Converter.Pappel2Strings
 *
 * @extends Pappel.Converter.Root
 */

import Converter from './Root';

class Pappel2Strings extends Converter {

  constructor(params) {
    super(params);
    this._logger.setPrefix({
      prefix: 'Pappel.Converter.Pappel2Strings'
    });
  }

  get contentBoilerplateBefore() {
    return '/*' + "\r\n" + '  Localizable.strings' + "\r\n" + "\r\n" + '  Generated by Pappel.io' + "\r\n" + '  */' + "\r\n";
  }

  get contentBoilerplateAfter() {
    return '';
  }


  /**
   * @method convert 
   *
   * @param {Object} params
   * @param {Object} params.pappel
   * @param {String} [params.language='']
   */
  convert(params) {
    this._logger.info('>> #convert');
    var
      o = params || {},
      pappel = o.pappel || null,
      language = o.language || null,

      possibleLanguages = null;

    if (pappel === null) {
      return null;
    }

    possibleLanguages = Object.keys(pappel[Object.keys(pappel)[0]]);

    if (language === null || possibleLanguages.indexOf(language) === -1) {
      language = possibleLanguages[0];
    }

    var file = '';

    for (var key in pappel) {
      var transformedString = this.transformString({
        str: pappel[key][language]
      });
      file += ['"', key, '" = "', transformedString, '";', "\r\n"].join('');
    }

    this._logger.info('<< #convert');
    return file;

  }

  /**
   * @method transformString
   * 
   * @param {Object} params
   * @param {String} params.str
   */

  transformString(params) {
    this._logger.info('>> #transformString');
    var tStr = this._vars.transformAnonymousPappel2Strings({
      str: params.str
    });
    this._logger.info('<< #transformString');
    return tStr;

  }

}

module.exports = Pappel2Strings;
